# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://gitcafe.com/akuandev/Specs.git'
target 'CloudSong' do
	pod 'AFNetworking'
	pod 'MJRefresh', '~> 2.0.1'
	pod 'ZXingObjC', '~> 3.1.0'
	pod 'MJExtension', '~> 0.3.2'
	pod 'libWeChatSDK', '~> 1.5'
#    pod 'SVProgressHUD'
    pod 'SDWebImage', '~> 3.7.2'
    pod 'Masonry', '~> 0.6.1'
    pod 'OBShapedButton'
    pod 'FXBlurView', '~> 1.6.3'
    pod 'UMengAnalytics'
	pod 'UMengSocial', :podspec => 'ThirdPartySDK/UMengSocial/UMengSocial.podspec'
	pod 'JPush', :podspec => 'ThirdPartySDK/JPush/JPush.podspec'
    #    pod 'RSKImageCropper', '~> 1.2.0'
end

target 'CloudSongTests' do

end

