# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'RecordTime' do
pod 'FMDB'
pod 'Masonry'
pod 'RESideMenu', '~> 4.0.7'
pod 'pop', :git => 'https://github.com/facebook/pop.git'
pod 'SVProgressHUD', '~> 1.1.3'
end

target 'RecordTimeTests' do

end

